### ISSUE TITLE
Не получается подгрузить файл конфигураций

### ISSUE THREAD

**Issue by GalYulia** [al-pacino/LSPL-2#1]
Добрый день! Подскажите, пожалуйста, в чем может быть ошибка. Скомпилила проект через VS2017, прописала параметры командной строки. Но при загрузке lspl3config.json происходит ошибка.
Вот лог:
Loading configuration validation scheme...
Loading configuration from file '../lspl3config.json'...
Parse config '../lspl3config.json' error at char 0: The document is empty.

Заранее спасибо за Ваше внимание.

**Comment by al-pacino** [comment]
@GalYulia, добрый день!
В сообщении об ошибке сказано "The document is empty.", такой вывод в том числе свидетельствует о том, что файла не существует либо он не найден.
Путь `../lspl3config.json` (как и другие относительные пути разрешаются относительно рабочего каталога). При запуске из Visual Studio рабочий каталог совпадает с каталогом проекта, т.е. правильные аргументы командной строки в данном случае будут такими: `lspl3config.json tests/Patterns.txt tests/2001_A_Space_Odyssey.json ""`.

**Comment by GalYulia** [comment]
спасибо большое!
